remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: "EC M202A Project â€“ Structured Reasoning for Sensor Data: Human Activity Recognition with GraphRAG"
description: "Course project website for EC M202A / CS M213A"
# For user pages, url should be "https://username.github.io" and baseurl: ""
# For project pages, url: "https://username.github.io" and baseurl: "/repo-name"
url: "https://P1UMA93.github.io"        # replace UCLA-ECEM202A with your github id
baseurl: "/ECEM202A_2025Fall_Project_7"    # replace ecem202a_project with your project name, e.g., "/ECEM202A_2025Fall_Project_1"

markdown: kramdown
kramdown:
  input: GFM

# Necessary for GitHub Pages
plugins: 
- jekyll-remote-theme

relative_links:
  enabled: true
  collections: true
